from tkinter import *
import mysql.connector
from tkinter import ttk
from tkinter import ttk,messagebox
from PIL import ImageTk

def add():
    if mem1.get()=="" or ref1.get()=="" or name1.get()=="" or adr1.get()=="" or em1.get()=="" or mob1.get()=="" or courselist.get()=="" or department1.get()=="" or bkid1.get()=="" or  bkt1.get()=="" or au1.get()=="" or  dob1.get()=="" or  dd1.get()=="" or  dl1.get()=="" :
       messagebox.showerror("Error","All fields are required")
    else:
     mem=mem1.get()
     ref=ref1.get()
     nam=name1.get()
     adr=adr1.get()
     email=em1.get()
     mob=mob1.get()
     course1=courselist.get()
     dep=department1.get()
     bkid=bkid1.get()
     bkt= bkt1.get()
     au=au1.get()
     dob=dob1.get()
     dd=dd1.get()
     dl=dl1.get()
     db=mysql.connector.connect(host="localhost",user="root",password="",database="sd")
     mycursor=db.cursor()
     try:
        sql="insert into library(memtype,reference,Name,Address,email,mob,course,dep,bookid,booktitle,author,dob,dd,dl)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
        val=(mem,ref,nam,adr,email,mob,course1,dep,bkid,bkt,au,dob,dd,dl)
        mycursor.execute(sql,val)
        db.commit()
        messagebox.showinfo("information","Record Inserted successfully")
        fectdata()
        cleardata()
     except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()
def fectdata():
    mem = mem1.get()
    ref = ref1.get()
    nam = name1.get()
    adr = adr1.get()
    email = em1.get()
    mob = mob1.get()
    course1 = courselist.get()
    dep = department1.get()
    bkid = bkid1.get()
    bkt = bkt1.get()
    au = au1.get()
    dob = dob1.get()
    dd = dd1.get()
    dl = dl1.get()
    db=mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    mycursor.execute("select * from library")
    rows=mycursor.fetchall()
    if len(rows)!=0:
        studtab.delete(*studtab.get_children())
    for row in rows:
       studtab.insert('',END,values=row)
    db.commit()
    db.close()
def cleardata():
    mem1.delete(0, 'end')
    ref1.delete(0, 'end')
    name1.delete(0, 'end')
    adr1.delete(0, 'end')
    em1.delete(0, 'end')
    mob1.delete(0, 'end')
    courselist.delete(0, 'end')
    department1.delete(0, 'end')
    bkid1.delete(0, 'end')
    bkt1.delete(0, 'end')
    au1.delete(0, 'end')
    dob1.delete(0, 'end')
    dd1.delete(0 ,'end')
    dl1.delete(0, 'end')
    name1.focus_set()
def getdata(event):
    currow=studtab.focus()
    contents=studtab.item(currow)
    row=contents['values']
    mem1.delete(0, END)
    ref1.delete(0, END)
    name1.delete(0, END)
    adr1.delete(0, END)
    em1.delete(0, END)
    mob1.delete(0, END)
    courselist.delete(0, END)
    department1.delete(0, END)
    bkid1.delete(0, END)
    bkt1.delete(0, END)
    au1.delete(0, END)
    dob1.delete(0, END)
    dd1.delete(0, END)
    dl1.delete(0, END)
    mem1.insert(0,row[0])
    ref1.insert(0,row[1])
    name1.insert(0,row[2])
    adr1.insert(0,row[3])
    em1.insert(0, row[4])
    mob1.insert(0, row[5])
    courselist.insert(0, row[6])
    department1.insert(0, row[7])
    bkid1.insert(0, row[8])
    bkt1.insert(0, row[9])
    au1.insert(0, row[11])
    dob1.insert(0, row[2])
    dd1.insert(0, row[7])
    dl1.insert(0,row[8])
def update():
    mem = mem1.get()
    ref = ref1.get()
    nam = name1.get()
    adr = adr1.get()
    email = em1.get()
    mob = mob1.get()
    course1 = courselist.get()
    dep = department1.get()
    bkid = bkid1.get()
    bkt = bkt1.get()
    au = au1.get()
    dob = dob1.get()
    dd = dd1.get()
    dl = dl1.get()
    db = mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    try:
        sql = "update library set memtype=%s,reference=%s,Address=%s,email=%s,mob=%s,course=%s,dep=%s,bookid=%s,booktitle=%s,author=%s,dob=%s,dd=%s,dl=%s where Name=%s"
        val = (mem,ref,adr,email,mob,course1,dep,bkid,bkt,au,dob,dd,dl,nam)
        mycursor.execute(sql, val)
        db.commit()
        messagebox.showinfo("information", "Record Updated successfully")
        mem1.delete(0, END)
        ref1.delete(0, END)
        name1.delete(0, END)
        adr1.delete(0, END)
        em1.delete(0, END)
        mob1.delete(0, END)
        courselist.delete(0, END)
        department1.delete(0, END)
        bkid1.delete(0, END)
        bkt1.delete(0, END)
        au1.delete(0, END)
        dob1.delete(0, END)
        dd1.delete(0, END)
        dl1.delete(0, END)
        fectdata()
        cleardata()
    except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()
def delete1():
    nam=name1.get()
    db=mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    try:
        sql ="delete from library where Name=%s"
        val = (nam,)
        mycursor.execute(sql, val)
        db.commit()
        messagebox.showinfo("information", "Record Deleted successfully")
        mem1.delete(0, END)
        ref1.delete(0, END)
        name1.delete(0, END)
        adr1.delete(0, END)
        em1.delete(0, END)
        mob1.delete(0, END)
        courselist.delete(0, END)
        department1.delete(0, END)
        bkid1.delete(0, END)
        bkt1.delete(0, END)
        au1.delete(0, END)
        dob1.delete(0, END)
        dd1.delete(0, END)
        dl1.delete(0, END)
        fectdata()
        cleardata()
    except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()

def back():
	rt.destroy()
	import admimain

def fectdata1():
    ser1=comboser.get()
    lsearch1 = lsearch.get()
    db = mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    mycursor.execute("select * from library where "+str(ser1)+" LIKE '%"+str(lsearch1)+"%'")
    rows=mycursor.fetchall()
    if len(rows)!=0:
        studtab.delete(*studtab.get_children())
    for row in rows:
       studtab.insert('',END,values=row)
    db.commit()
    db.close()
rt=Tk()
rt.title("Library Details ")
rt.geometry("1400x900+0+0")
bg=ImageTk.PhotoImage(file="pic.jpg")
bglb=Label(rt,image=bg)
bglb.place(x=0,y=0,relwidth=1,relheight=1)
title=Label(rt,text="Library System",bd=5,relief=GROOVE,font=("constantia",30,"bold"),bg="yellow",fg="black")
title.pack(side=TOP,fill=X)
managefrm=Frame(rt,bd=4,relief=RIDGE,bg="white")
managefrm.place(x=20,y=100,width=520,height=690)
#mtitle=Label(managefrm,text="Library Details",font=("times new roman",20,"bold"),fg="black",bg="white")
#mtitle.grid(row=0,columnspan=2,pady=20)
mem=Label(managefrm,text="Member Type",font=("times new roman",15,"bold"),fg="black",bg="white")
mem.grid(row=1,column=0,pady=10,padx=50,sticky="w")
mem1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
mem1.grid(row=1,column=1,pady=10,padx=20,sticky="w")
ref=Label(managefrm,text="Reference no",font=("times new roman",15,"bold"),fg="black",bg="white")
ref.grid(row=2,column=0,pady=10,padx=50,sticky="w")
ref1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
ref1.grid(row=2,column=1,pady=10,padx=20,sticky="w")
name=Label(managefrm,text="Name",font=("times new roman",15,"bold"),fg="black",bg="white")
name.grid(row=3,column=0,pady=10,padx=50,sticky="w")
name1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
name1.grid(row=3,column=1,pady=10,padx=20,sticky="w")
adr=Label(managefrm,text="Address",font=("times new roman",15,"bold"),fg="black",bg="white")
adr.grid(row=4,column=0,pady=10,padx=50,sticky="w")
adr1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
adr1.grid(row=4,column=1,pady=10,padx=20,sticky="w")
em=Label(managefrm,text="Email id",font=("times new roman",15,"bold"),fg="black",bg="white")
em.grid(row=5,column=0,pady=10,padx=50,sticky="w")
em1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
em1.grid(row=5,column=1,pady=10,padx=20,sticky="w")
mob=Label(managefrm,text="Mobile no.",font=("times new roman",15,"bold"),fg="black",bg="white")
mob.grid(row=6,column=0,pady=10,padx=50,sticky="w")
mob1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
mob1.grid(row=6,column=1,pady=10,padx=20,sticky="w")
course=Label(managefrm,text="Course",font=("times new roman",15,"bold"),fg="black",bg="white")
course.grid(row=7,column=0,pady=10,padx=50,sticky="w")
courselist=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
courselist.grid(row=7,column=1,pady=10,padx=20,sticky="w")
department=Label(managefrm,text="Department",font=("times new roman",15,"bold"),fg="black",bg="white")
department.grid(row=8,column=0,pady=10,padx=50,sticky="w")
department1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
department1.grid(row=8,column=1,pady=10,padx=20,sticky="w")
bkid=Label(managefrm,text="Book id",font=("times new roman",15,"bold"),fg="black",bg="white")
bkid.grid(row=9,column=0,pady=10,padx=50,sticky="w")
bkid1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
bkid1.grid(row=9,column=1,pady=10,padx=20,sticky="w")
bkt=Label(managefrm,text="Book Title",font=("times new roman",15,"bold"),fg="black",bg="white")
bkt.grid(row=10,column=0,pady=10,padx=50,sticky="w")
bkt1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
bkt1.grid(row=10,column=1,pady=10,padx=20,sticky="w")
au=Label(managefrm,text="Author",font=("times new roman",15,"bold"),fg="black",bg="white")
au.grid(row=11,column=0,pady=10,padx=50,sticky="w")
au1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
au1.grid(row=11,column=1,pady=10,padx=20,sticky="w")
dob=Label(managefrm,text="Date of Borrowed",font=("times new roman",15,"bold"),fg="black",bg="white")
dob.grid(row=12,column=0,pady=10,padx=50,sticky="w")
dob1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
dob1.grid(row=12,column=1,pady=10,padx=20,sticky="w")
dd=Label(managefrm,text="Date of Due",font=("times new roman",15,"bold"),fg="black",bg="white")
dd.grid(row=13,column=0,pady=10,padx=50,sticky="w")
dd1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
dd1.grid(row=13,column=1,pady=10,padx=20,sticky="w")
dl=Label(managefrm,text="Days in Loan",font=("times new roman",15,"bold"),fg="black",bg="white")
dl.grid(row=14,column=0,pady=10,padx=50,sticky="w")
dl1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
dl1.grid(row=14,column=1,pady=10,padx=20,sticky="w")
#btnfrm=Frame(managefrm,bd=4,relief=RIDGE,bg="gray")
#btnfrm.place(x=10,y=530,width=400,height=100)


#addbt=Button(btnfrm,text="ADD",command=add,width=10).grid(row=0,column=0,padx=10,pady=10)
#updatebt=Button(btnfrm,text="UPDATE",command=update,width=10).grid(row=0,column=1,padx=10,pady=10)
#detebt=Button(btnfrm,text="DELETE",command=delete1,width=10).grid(row=0,column=2,padx=10,pady=10)
#clrt=Button(btnfrm,text="CLEAR",command=cleardata,width=10).grid(row=0,column=3,padx=10,pady=10)
#backbt=Button(btnfrm,text="BACK",command=back,width=10).grid(row=7,column=0,padx=10,pady=10)
detfrm=Frame(rt,bd=4,relief=RIDGE,bg="yellow")
detfrm.place(x=500,y=100,width=850,height=690)
lsearch=Label(detfrm,text="Search By",font=("times new roman",15,"bold"),bg="yellow")
lsearch.grid(row=0,column=0,padx=10,pady=20,sticky="w")
comboser=ttk.Combobox(detfrm,font=("times new roman",15,"bold"),width=10,state='readonly')
comboser['values']=("name",)
comboser.grid(row=0,column=1,padx=20,pady=10,sticky="w")
lsearch=Entry(detfrm,font=("Times New Roman",15,"bold"),bd=5,relief=GROOVE)
lsearch.grid(row=0,column=2,pady=10,padx=20,sticky="w")
serbt=Button(detfrm,text="Search",command=fectdata1,font=("Times New Roman",10,"bold"),width=10,pady=5).grid(row=0,column=3,padx=10,pady=10)
showbt=Button(detfrm,text="Show All",command=fectdata,font=("Times New Roman",10,"bold"),width=10,pady=5).grid(row=0,column=4,padx=10,pady=10)
tabfrm=Frame(detfrm,bd=4,relief=RIDGE,bg="lightblue")
tabfrm.place(x=10,y=70,width=800,height=450)
btnfrm=Frame(detfrm,bd=4,relief=RIDGE,bg="gray")
btnfrm.place(x=10,y=530,width=400,height=100)

addbt=Button(btnfrm,text="ADD",command=add,width=10).grid(row=0,column=0,padx=10,pady=10)
updatebt=Button(btnfrm,text="UPDATE",command=update,width=10).grid(row=0,column=1,padx=10,pady=10)
detebt=Button(btnfrm,text="DELETE",command=delete1,width=10).grid(row=0,column=2,padx=10,pady=10)
clrt=Button(btnfrm,text="CLEAR",command=cleardata,width=10).grid(row=0,column=3,padx=10,pady=10)
backbt=Button(btnfrm,text="BACK",command=back,width=10).grid(row=7,column=0,padx=10,pady=10)
scrollx=Scrollbar(tabfrm,orient=HORIZONTAL)
scrolly=Scrollbar(tabfrm,orient=VERTICAL)
studtab=ttk.Treeview(tabfrm,columns=("member type","reference no","name","address","email","mobileno","course","department","bookid","booktitle","author","dob","dd","dl"),xscrollcommand=scrollx.set,yscrollcommand=scrolly.set)
scrollx.pack(side=BOTTOM,fill=X)
scrolly.pack(side=RIGHT,fill=Y)
scrollx.config(command=studtab.xview)
scrolly.config(command=studtab.yview)
studtab.heading("member type",text="Member Type")
studtab.heading("reference no",text="Reference no")
studtab.heading("name",text="Name")
studtab.heading("address",text="Address")
studtab.heading("email",text="Email")
studtab.heading("mobileno",text="Mobile no.")
studtab.heading("course",text="Course")
studtab.heading("department",text="Department")
studtab.heading("bookid",text="Book id")
studtab.heading("booktitle",text="Book Title")
studtab.heading("author",text="Author")
studtab.heading("dob",text="Date of Borrowed")
studtab.heading("dd",text="Date of Due")
studtab.heading("dl",text="Days in Loan")
studtab['show']="headings"
studtab.column("member type",width=100)
studtab.column("reference no",width=100)
studtab.column("name",width=100)
studtab.column("address",width=100)
studtab.column("email",width=100)
studtab.column("mobileno",width=100)
studtab.column("course",width=100)
studtab.column("department",width=100)
studtab.column("bookid",width=100)
studtab.column("booktitle",width=100)
studtab.column("author",width=100)
studtab.column("dob",width=100)
studtab.column("dd",width=100)
studtab.column("dl",width=100)
studtab.pack(fill=BOTH,expand=1)
studtab.bind("<ButtonRelease-1>",getdata)

fectdata()
rt.mainloop()