from tkinter import *
import mysql.connector
from tkinter import ttk
from tkinter import ttk,messagebox
from PIL import ImageTk

def add():
    if name1.get()=="" or rol1.get()=="" or unirol1.get()=="" or em1.get()=="" or mob1.get()=="" or adr1.get()=="" or courselist.get()=="" or department1.get()=="" or cs1.get()=="" or sgp1.get()=="" or pla1.get()=="" or cna1.get()=="" or  slda1.get()=="" :
       messagebox.showerror("Error","All fields are required")
    else:
     nam=name1.get()
     r1 = rol1.get()
     unir1 = unirol1.get()
     email = em1.get()
     mob = mob1.get()
     adr=adr1.get()
     course1=courselist.get()
     dep=department1.get()
     sem = cs1.get()
     sg = sgp1.get()
     pl=pla1.get()
     cn=cna1.get()
     sld=slda1.get()
     db=mysql.connector.connect(host="localhost",user="root",password="",database="sd")
     mycursor=db.cursor()
     try:
        sql="insert into caminfo(Name,rol,unirol,email,mob,Address,course,department,cs,sgp,placement,cn,sld)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
        val=(nam,r1,unir1,email,mob,adr,course1,dep,sem,sg,pl,cn,sld)
        mycursor.execute(sql,val)
        db.commit()
        messagebox.showinfo("information","Record Inserted successfully")
        fectdata()
        cleardata()
     except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()
def fectdata():
    nam = name1.get()
    r1 = rol1.get()
    unir1 = unirol1.get()
    email = em1.get()
    mob = mob1.get()
    adr = adr1.get()
    course1 = courselist.get()
    dep = department1.get()
    sem = cs1.get()
    sg = sgp1.get()
    pl = pla1.get()
    cn = cna1.get()
    sld = slda1.get()
    db=mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    mycursor.execute("select * from caminfo")
    rows=mycursor.fetchall()
    if len(rows)!=0:
        studtab.delete(*studtab.get_children())
    for row in rows:
       studtab.insert('',END,values=row)
    db.commit()
    db.close()
def cleardata():
    name1.delete(0, 'end')
    rol1.delete(0, 'end')
    unirol1.delete(0, 'end')
    em1.delete(0, 'end')
    mob1.delete(0, 'end')
    adr1.delete(0, 'end')
    courselist.delete(0, 'end')
    department1.delete(0, 'end')
    cs1.delete(0, 'end')
    sgp1.delete(0, 'end')
    pla1.delete(0, 'end')
    cna1.delete(0, 'end')
    slda1.delete(0 ,'end')
    name1.focus_set()
def getdata(event):
    currow=studtab.focus()
    contents=studtab.item(currow)
    row=contents['values']
    name1.delete(0, END)
    rol1.delete(0, END)
    unirol1.delete(0, END)
    em1.delete(0, END)
    mob1.delete(0, END)
    adr1.delete(0, END)
    courselist.delete(0, END)
    department1.delete(0, END)
    cs1.delete(0, END)
    sgp1.delete(0, END)
    pla1.delete(0, END)
    cna1.delete(0, END)
    slda1.delete(0, END)
    name1.insert(0, row[0])
    rol1.insert(0, row[1])
    unirol1.insert(0, row[2])
    em1.insert(0, row[3])
    mob1.insert(0, row[4])
    adr1.insert(0,row[5])
    courselist.insert(0, row[6])
    department1.insert(0, row[7])
    cs1.insert(0, row[8])
    sgp1.insert(0, row[9])
    pla1.insert(0, row[10])
    cna1.insert(0, row[11])
    slda1.insert(0, row[12])
def update():
    nam = name1.get()
    r1 = rol1.get()
    unir1 = unirol1.get()
    email = em1.get()
    mob = mob1.get()
    adr = adr1.get()
    course1 = courselist.get()
    dep = department1.get()
    sem = cs1.get()
    sg = sgp1.get()
    pl = pla1.get()
    cn = cna1.get()
    sld = slda1.get()
    db = mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    try:
        sql = "update caminfo set rol=%s,unirol=%s,email=%s,mob=%s,Address=%s,course=%s,department=%s,cs=%s,sgp=%s,placement=%s,cn=%s,sld=%s where Name=%s"
        val = (r1,unir1,email,mob,adr,course1,dep,sem,sg,pl,cn,sld,nam)
        mycursor.execute(sql, val)
        db.commit()
        messagebox.showinfo("information", "Record Updated successfully")
        name1.delete(0, END)
        rol1.delete(0, END)
        unirol1.delete(0, END)
        em1.delete(0, END)
        mob1.delete(0, END)
        adr1.delete(0, END)
        courselist.delete(0, END)
        department1.delete(0, END)
        cs1.delete(0, END)
        sgp1.delete(0, END)
        pla1.delete(0, END)
        cna1.delete(0, END)
        slda1.delete(0, END)
        fectdata()
        cleardata()
    except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()
def delete1():
    nam=name1.get()
    db=mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    try:
        sql ="delete from caminfo where Name=%s"
        val = (nam,)
        mycursor.execute(sql, val)
        db.commit()
        messagebox.showinfo("information", "Record Deleted successfully")
        name1.delete(0, END)
        rol1.delete(0, END)
        unirol1.delete(0, END)
        em1.delete(0, END)
        mob1.delete(0, END)
        adr1.delete(0, END)
        courselist.delete(0, END)
        department1.delete(0, END)
        cs1.delete(0, END)
        sgp1.delete(0, END)
        pla1.delete(0, END)
        cna1.delete(0, END)
        slda1.delete(0, END)
        fectdata()
        cleardata()
    except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()

def back():
	rt.destroy()
	import admimain

def fectdata1():
    ser1=comboser.get()
    lsearch1 = lsearch.get()
    db = mysql.connector.connect(host="localhost", user="root", password="", database="sd")
    mycursor = db.cursor()
    mycursor.execute("select * from caminfo where "+str(ser1)+" LIKE '%"+str(lsearch1)+"%'")
    rows=mycursor.fetchall()
    if len(rows)!=0:
        studtab.delete(*studtab.get_children())
    for row in rows:
       studtab.insert('',END,values=row)
    db.commit()
    db.close()
rt=Tk()
rt.title("Placement Details")
rt.geometry("1400x900+0+0")
bg=ImageTk.PhotoImage(file="pic.jpg")
bglb=Label(rt,image=bg)
bglb.place(x=0,y=0,relwidth=1,relheight=1)
title=Label(rt,text="Placement Details",bd=5,relief=GROOVE,font=("constantia",30,"bold"),bg="yellow",fg="black")
title.pack(side=TOP,fill=X)
managefrm=Frame(rt,bd=4,relief=RIDGE,bg="white")
managefrm.place(x=20,y=100,width=520,height=690)
#mtitle=Label(managefrm,text="Library Details",font=("times new roman",20,"bold"),fg="black",bg="white")
#mtitle.grid(row=0,columnspan=2,pady=20)
name=Label(managefrm,text="Name",font=("times new roman",15,"bold"),fg="black",bg="white")
name.grid(row=1,column=0,pady=10,padx=50,sticky="w")
name1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
name1.grid(row=1,column=1,pady=10,padx=20,sticky="w")
rol=Label(managefrm,text="Roll",font=("times new roman",15,"bold"),fg="black",bg="white")
rol.grid(row=2,column=0,pady=10,padx=50,sticky="w")
rol1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
rol1.grid(row=2,column=1,pady=10,padx=20,sticky="w")
unirol=Label(managefrm,text="Uni.Roll",font=("times new roman",15,"bold"),fg="black",bg="white")
unirol.grid(row=3,column=0,pady=10,padx=50,sticky="w")
unirol1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
unirol1.grid(row=3,column=1,pady=10,padx=20,sticky="w")
em=Label(managefrm,text="Email id",font=("times new roman",15,"bold"),fg="black",bg="white")
em.grid(row=4,column=0,pady=10,padx=50,sticky="w")
em1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
em1.grid(row=4,column=1,pady=10,padx=20,sticky="w")
mob=Label(managefrm,text="Mobile no.",font=("times new roman",15,"bold"),fg="black",bg="white")
mob.grid(row=5,column=0,pady=10,padx=50,sticky="w")
mob1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
mob1.grid(row=5,column=1,pady=10,padx=20,sticky="w")
adr=Label(managefrm,text="Address",font=("times new roman",15,"bold"),fg="black",bg="white")
adr.grid(row=6,column=0,pady=10,padx=50,sticky="w")
adr1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
adr1.grid(row=6,column=1,pady=10,padx=20,sticky="w")
course=Label(managefrm,text="Course",font=("times new roman",15,"bold"),fg="black",bg="white")
course.grid(row=7,column=0,pady=10,padx=50,sticky="w")
courselist=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
courselist.grid(row=7,column=1,pady=10,padx=20,sticky="w")
department=Label(managefrm,text="Department",font=("times new roman",15,"bold"),fg="black",bg="white")
department.grid(row=8,column=0,pady=10,padx=50,sticky="w")
department1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
department1.grid(row=8,column=1,pady=10,padx=20,sticky="w")
cs=Label(managefrm,text="Current Semester",font=("times new roman",15,"bold"),fg="black",bg="white")
cs.grid(row=9,column=0,pady=10,padx=50,sticky="w")
cs1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
cs1.grid(row=9,column=1,pady=10,padx=20,sticky="w")
sgp=Label(managefrm,text="SGPA Obtained",font=("times new roman",15,"bold"),fg="black",bg="white")
sgp.grid(row=10,column=0,pady=10,padx=50,sticky="w")
sgp1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
sgp1.grid(row=10,column=1,pady=10,padx=20,sticky="w")
pla=Label(managefrm,text="Placement",font=("times new roman",15,"bold"),fg="black",bg="white")
pla.grid(row=11,column=0,pady=10,padx=50,sticky="w")
pla1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
pla1.grid(row=11,column=1,pady=10,padx=20,sticky="w")
cna=Label(managefrm,text="Name of Company",font=("times new roman",15,"bold"),fg="black",bg="white")
cna.grid(row=12,column=0,pady=10,padx=50,sticky="w")
cna1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
cna1.grid(row=12,column=1,pady=10,padx=20,sticky="w")
slda=Label(managefrm,text="Date of selection",font=("times new roman",15,"bold"),fg="black",bg="white")
slda.grid(row=13,column=0,pady=10,padx=50,sticky="w")
slda1=Entry(managefrm,font=("times new roman",15,"bold"),fg="black",bg="white")
slda1.grid(row=13,column=1,pady=10,padx=20,sticky="w")
#btnfrm=Frame(managefrm,bd=4,relief=RIDGE,bg="gray")
#btnfrm.place(x=10,y=530,width=400,height=100)


#addbt=Button(btnfrm,text="ADD",command=add,width=10).grid(row=0,column=0,padx=10,pady=10)
#updatebt=Button(btnfrm,text="UPDATE",command=update,width=10).grid(row=0,column=1,padx=10,pady=10)
#detebt=Button(btnfrm,text="DELETE",command=delete1,width=10).grid(row=0,column=2,padx=10,pady=10)
#clrt=Button(btnfrm,text="CLEAR",command=cleardata,width=10).grid(row=0,column=3,padx=10,pady=10)
#backbt=Button(btnfrm,text="BACK",command=back,width=10).grid(row=7,column=0,padx=10,pady=10)
detfrm=Frame(rt,bd=4,relief=RIDGE,bg="yellow")
detfrm.place(x=500,y=100,width=850,height=690)
lsearch=Label(detfrm,text="Search By",font=("times new roman",15,"bold"),bg="yellow")
lsearch.grid(row=0,column=0,padx=10,pady=20,sticky="w")
comboser=ttk.Combobox(detfrm,font=("times new roman",15,"bold"),width=10,state='readonly')
comboser['values']=("name",)
comboser.grid(row=0,column=1,padx=20,pady=10,sticky="w")
lsearch=Entry(detfrm,font=("Times New Roman",15,"bold"),bd=5,relief=GROOVE)
lsearch.grid(row=0,column=2,pady=10,padx=20,sticky="w")
serbt=Button(detfrm,text="Search",command=fectdata1,font=("Times New Roman",10,"bold"),width=10,pady=5).grid(row=0,column=3,padx=10,pady=10)
showbt=Button(detfrm,text="Show All",command=fectdata,font=("Times New Roman",10,"bold"),width=10,pady=5).grid(row=0,column=4,padx=10,pady=10)
tabfrm=Frame(detfrm,bd=4,relief=RIDGE,bg="lightblue")
tabfrm.place(x=10,y=70,width=800,height=450)
btnfrm=Frame(detfrm,bd=4,relief=RIDGE,bg="gray")
btnfrm.place(x=10,y=530,width=400,height=100)

addbt=Button(btnfrm,text="ADD",command=add,width=10).grid(row=0,column=0,padx=10,pady=10)
updatebt=Button(btnfrm,text="UPDATE",command=update,width=10).grid(row=0,column=1,padx=10,pady=10)
detebt=Button(btnfrm,text="DELETE",command=delete1,width=10).grid(row=0,column=2,padx=10,pady=10)
clrt=Button(btnfrm,text="CLEAR",command=cleardata,width=10).grid(row=0,column=3,padx=10,pady=10)
backbt=Button(btnfrm,text="BACK",command=back,width=10).grid(row=7,column=0,padx=10,pady=10)
scrollx=Scrollbar(tabfrm,orient=HORIZONTAL)
scrolly=Scrollbar(tabfrm,orient=VERTICAL)
studtab=ttk.Treeview(tabfrm,columns=("name","roll","uniroll","email","mobileno","address","course","department","currentsem","sgpa","placement","company","date of selection"),xscrollcommand=scrollx.set,yscrollcommand=scrolly.set)
scrollx.pack(side=BOTTOM,fill=X)
scrolly.pack(side=RIGHT,fill=Y)
scrollx.config(command=studtab.xview)
scrolly.config(command=studtab.yview)
studtab.heading("name",text="Name")
studtab.heading("roll",text="Roll")
studtab.heading("uniroll",text="Uni.Roll")
studtab.heading("email",text="Email")
studtab.heading("mobileno",text="Mobile no.")
studtab.heading("address",text="Address")
studtab.heading("course",text="Course")
studtab.heading("department",text="Department")
studtab.heading("currentsem",text="Current Sem")
studtab.heading("sgpa",text="SGPA")
studtab.heading("placement",text="Placement")
studtab.heading("company",text="Name of Company")
studtab.heading("date of selection",text="Date of selection")
studtab['show']="headings"
studtab.column("name",width=100)
studtab.column("roll",width=100)
studtab.column("uniroll",width=100)
studtab.column("email",width=100)
studtab.column("mobileno",width=100)
studtab.column("address",width=100)
studtab.column("course",width=100)
studtab.column("department",width=100)
studtab.column("currentsem",width=100)
studtab.column("sgpa",width=100)
studtab.column("placement",width=100)
studtab.column("company",width=100)
studtab.column("date of selection",width=100)
studtab.pack(fill=BOTH,expand=1)
studtab.bind("<ButtonRelease-1>",getdata)

fectdata()
rt.mainloop()