from tkinter import*
import mysql.connector
from tkinter import ttk
from tkinter import ttk,messagebox
from tkcalendar import DateEntry
from PIL import Image,ImageTk #pip install Pillow
#def login_window():
    #rt.destroy()
    #import login
def back():
	rt.destroy()
	import home

def Add():
    if fen.get()=="" or ln.get()=="" or cont.get()=="" or courselist.get()=="" or email1.get()==""or pass1.get()=="" or pass2.get()=="":
        messagebox.showerror("Error","All fields are required")
    elif pass1.get()!=pass2.get():
        messagebox.showerror("Error", "Check Password")
    elif vag.get()==0:
        messagebox.showerror("Error", "You have to agree to our term and codition")
    else:
     nm=fen.get()
     lm=ln.get()
     cont1=cont.get()
     dob1=cal.get()
     course1=courselist.get()
     gen1=radio.get()
     e=email1.get()
     password1=pass1.get()
     cpass=pass2.get()
     db=mysql.connector.connect(host="localhost",user="root",password="",database="sd")
     mycursor=db.cursor()
     try:
        sql="insert into college(fnm,lnm,contact,dob,course,gen,email,password,cpass)values(%s,%s,%s,%s,%s,%s,%s,%s,%s)"
        val=(nm,lm,cont1,dob1,course1,gen1,e,password1,cpass)
        mycursor.execute(sql,val)
        db.commit()
        lastid=mycursor.lastrowid
        messagebox.showinfo("information","Record Inserted successfully")
        fen.delete(0,END)
        ln.delete(0, END)
        cont.delete(0,END)
        cal.delete(0,END)
        courselist.delete(0,END)
        radio.delete(0,END)
        email1.delete(0,END)
        pass1.delete(0,END)
        pass2.delete(0,END)
        nm.focus_set()
     except EXCEPTION as e:
        print(e)
        db.rollback()
        db.close()

rt=Tk()
rt.title("Register")
rt.geometry("1400x900+0+0")
bg=ImageTk.PhotoImage(file="pic.jpg")
bglb=Label(rt,image=bg)
bglb.place(x=0,y=0,relwidth=1,relheight=1)
frame=Frame(rt,bg='white')
frame.place(x=520,y=100,width=800,height=630)
reg=Label(frame,text="REGISTER HERE",font=("Times New Roman",25,"bold"),fg="black",bg="yellow")
reg.place(x=20,y=20)
fnm=Label(frame,text="First Name",font=("Times New Roman",15,"bold"),bg="white")
fnm.place(x=30,y=100)
fen=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
fen.place(x=30,y=130,width=250)
lnm=Label(frame,text="Last Name",font=("Times New Roman",15,"bold"),bg="white")
lnm.place(x=370,y=100)
ln=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
ln.place(x=370,y=130,width=250)
contact=Label(frame,text="Contact Number",font=("Times New Roman",15,"bold"),bg="white")
contact.place(x=30,y=170)
cont=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
cont.place(x=30,y=200,width=250)
dob=Label(frame,text="DOB",font=("Times New Roman",15,"bold"),bg="white")
dob.place(x=370,y=170)
cal = DateEntry(frame,font=("Times New Roman",15,"bold"),background='gray',foreground='white',borderwidth=2)
cal.place(x=370,y=200,width=250,height=30)
course=Label(frame,text="Course",bg="white",font=("Times New Roman",15,"bold"))
course.place(x=30,y=240)
courselist=ttk.Combobox(frame,textvariable="vcourse",font=("Times New Roman",15,"bold"),state="readonly")
courselist["values"]=("SELECT","BTECH","BCA","MCA","MTECH")
courselist.place(x=30,y=280,width=250)
courselist.current(0)
gen=Label(frame,text="Gender",font=("Times New Roman",15,"bold"),bg="white")
gen.place(x=370,y=250)
radio = StringVar()
m = Radiobutton(frame,text="Male",variable=radio,value="Male",bg="white",font=("Times New Roman",15,"bold"))
m.place(x=370,y=280,width=130,height=20)
f=Radiobutton(frame, text="Female", variable=radio, value="Female",bg="White",font=("Times New Roman",15,"bold"))
f.place(x=370,y=300,width=150,height=20)
email=Label(frame,text="Email",font=("Times New Roman",15,"bold"),bg="white")
email.place(x=30,y=330)
email1=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
email1.place(x=30,y=360,width=250)
password=Label(frame,text="Password",font=("Times New Roman",15,"bold"),bg="white")
password.place(x=370,y=330)
pass1=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
pass1.place(x=370,y=360,width=250)
pass1.config(show="*")
cnpassword=Label(frame,text="Confirm Password",font=("Times New Roman",15,"bold"),bg="white")
cnpassword.place(x=370,y=400)
pass2=ttk.Entry(frame,font=("Times New Roman",15,"bold"))
pass2.place(x=370,y=430,width=250)
pass2.config(show="*")
vag=IntVar()
chk=Checkbutton(frame,variable=vag,text="I Agree the Terms and Conditions",font=("Times New Roman",10,"bold"),onvalue=1,offvalue=0)
chk.place(x=30,y=460)
b1=Button(frame,text="Register",command=Add,font=("Times New Roman",15,"bold"))
b1.place(x=30,y=510)
b2=Button(frame,text="Home",command=back,font=("Times New Roman",15,"bold"))
b2.place(x=370,y=510)
rt.mainloop()
